# Site Settings
title: SYZC's Translation
email: syc0308tw@gmail.com
description: >
  A website for hosting translations of chinese webnovels.
baseurl: ""
url: "https://syzctranslations.github.io"
permalink: none
paginate: 10
future: true

gems:
  - jekyll-seo-tag

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
collections: 
  translations:
    output: true
    permalink: /:collection/:categories/:name
kramdown:
  input: GFM